version: "3"
services:
  # Create frontend container
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-docker
    restart: always
    depends_on:
      - backend
  # Create backend container
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    container_name: backend-docker
    restart: always
